# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a73dd8b4592239d54018837d94d116a9acf0667d66e131f071a91036d4fe8283acb28ab9b5ae99c537706b2796d3085b072c2a4f54076e67e6ca6070073aafc7

test:
  secret_key_base: e9ce47296dd89726fdc8bcf2990ef65a0738d0161bc29fdb3449c30f59b03e00e5432b667d73510a83f9edc96f0983dafda67929d9f3cdd90821362ead2d64d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
